version: '2'
name: experimental-post-training
distribution_spec:
  description: Experimental template for post training
  container_image: null
  providers:
    inference:
    - remote::ollama
    post_training:
    - inline::torchtune
    datasetio:
    - inline::localfs
    - remote::huggingface
    telemetry:
    - inline::meta-reference
image_type: conda
